language: cpp

dist: trusty

os:
- linux

compiler: 
- gcc

script:
    ############################################################################
    # Build 
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON .. 
     - make
